Controllers/PhotoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Entities;
using Domain.Abstract;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class PhotoController : Controller
    {
        private IPhotoRepository repository;
        public PhotoController(IPhotoRepository repo)
        {
            this.repository=repo;
        }
        //
        // GET: /Photo/

        public ViewResult Albums(int userId, string album)
        {
            

            PhotoModelView photosUser = new PhotoModelView
            {
                Photos = repository.Photos
                .Where(p => p.UserID == userId&&(album==null||p.Albom==album))
                .OrderBy(p => p.Name),
                CurrentAlbum=album

            };

            ViewBag.UserId = userId;
                   
             
            return View(photosUser);
        }
        
        public ViewResult AddNewPhoto(int userId)
        {
            return View("Edit",new Photo());
        }
        public ViewResult Edit(int photoId)
        {
            Photo photoForEdit = repository.Photos
                .FirstOrDefault(ph => ph.PhotoID == photoId);
            return View(photoForEdit);
        }
        [HttpPost]
        public ActionResult Edit(Photo photoUser, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    photoUser.ImageMimeType = image.ContentType;
                    photoUser.ImageData = new byte[image.ContentLength];
                    image.InputStream.Read(photoUser.ImageData, 0, image.ContentLength);
                }
                repository.SavePhoto(photoUser);
                return RedirectToAction("Albums", new { userId=photoUser.UserID });
            }
            else
            {
                return View(photoUser);
            }
        }
        public ActionResult Delete(int photoId)
        {
            Photo deletePhoto = repository.DeletePhoto(photoId);
            if(deletePhoto!=null)
            {
                TempData["messageForPhoto"] = string.Format("{0} была удалена", deletePhoto.Name);
            }
            return RedirectToAction("Albums", new { userId = deletePhoto.UserID });
        }
        public FileContentResult GetPhoto(int photoId)
        {
            Photo photo = repository.Photos.FirstOrDefault(ph => ph.PhotoID == photoId);
            if (photo!=null)
            {
                return File(photo.ImageData, photo.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
    }
}

Controllers/SliderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Abstract;
using WebUI.Models;
namespace WebUI.Controllers
{
    public class SliderController : Controller
    {
        //
        // GET: /Slider/
        private IPhotoRepository repository;
        public SliderController(IPhotoRepository repo)
        {
            repository = repo;
        }
        public PartialViewResult SliderOfPhoto(int userId)
        {
            PhotoModelView photo = new PhotoModelView
            {
                Photos=repository.Photos
                .Where(p=>p.UserID==userId)
            };
            
            return PartialView(photo);
        }

    }
}

Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Abstract;
using Domain.Entities;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class UserController : Controller
    {
        private IUserRepository repository;
        public UserController(IUserRepository repo)
        {
            repository = repo;
        }
        public ViewResult MainPage(int userId)
        {
            User user = repository.Users
                .FirstOrDefault(p => p.UserID == userId);
            return View(user);
        }
        public ViewResult Login()
        {
            return View(new User());
        }
       [HttpPost]
        public ViewResult Login(User userEntered)
        {
            User user = repository.Users
                .FirstOrDefault(p => p.Email == userEntered.Email);
            if (user != null)
            {
                if (user.Password == userEntered.Password)
                {
                    return View("MainPage", user);
                }
                else
                {
                    TempData["message"] = string.Format("Password isn't correct");
                    return View(new User());
                }
            }
            else
            {
                TempData["message"] = string.Format("{0} is not found", userEntered.Email);
                return View(new User());
            }

        }
        public ViewResult Registration()
        {
            return View(new RegistrationModel());
        }

        [HttpPost]
        public ActionResult Registration(RegistrationModel registrDataUser, HttpPostedFileBase image)
        {
            User userForCheckedEmail = repository.Users
                .FirstOrDefault(p => p.Email == registrDataUser.Email);
            if (userForCheckedEmail == null)
            {
                User user = new User();
                if (ModelState.IsValid)
                {
                    if (image != null)
                    {
                        user.ImageMimeType = image.ContentType;
                        user.ImageData = new byte[image.ContentLength];
                        image.InputStream.Read(user.ImageData, 0, image.ContentLength);
                    }
                    user.Email = registrDataUser.Email;
                    user.Password = registrDataUser.Password;
                    user.Name = registrDataUser.Name;
                    user.Surname = registrDataUser.Surname;
                    user.UserID = registrDataUser.UserID;
                    user.Burthday = registrDataUser.Burthday;
                    user.NumberPhone = registrDataUser.NumberPhone;
                    repository.SaveUser(user);
                    return View("MainPage", user);
                }
                else
                {
                    return View(registrDataUser);
                }
            }
            else
            {
                return View(registrDataUser);

            }

        }
        public ActionResult About()
        {
            return PartialView();
        }
        public FileContentResult GetImage(int userId)
        {
            User user = repository.Users.FirstOrDefault(u => u.UserID == userId);
            if (user!=null)
	        {
		        return  File(user.ImageData, user.ImageMimeType);
	        }
            else
	        {
                return null;
	        }
        }

    }
}

Views/User/Login.cshtml
@model Domain.Entities.User

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Nav.cshtml";
}
<div class="col-md-3 col-lg-3 col-sm-3">
    @using (Html.BeginForm("Login", "User", new { htmlAttributes = new { @class = "form-horizontal" } }))
    {
        <fieldset>
            <div class="form-group">
                <div class="input-group margin-bottom-sm">
                    <span class="input-group-addon"><i class="fa fa-envelope-o fa-fw" aria-hidden="true"></i></span>
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-key fa-fw" aria-hidden="true"></i></span>
                    @Html.PasswordFor(model => model.Password, new { htmlAttributes = new { @lass = "form-control" } })
                </div>
            </div>
            
            <div class="form-group">
                <button class="btn btn-success " type="submit"> <i class="fa fa-sign-in " aria-hidden="true"></i> Войти</button>
                <a class="btn btn-success " href="User/Registration" > <i class="fa fa-address-card " aria-hidden="true"></i> Регистрация</a>
            </div>
        </fieldset>
    }
</div>
<div class="col-md-1 col-lg-1 col-sm-1 vcenter"></div>
<div class="col-md-8 col-lg-8 col-sm-8 vcenter">
    <div class="centering">
        <img src="/img/semya.jpg" width="604" height="402" class="img-rounded img-responsive" alt="Responsive image">
        <p class="text-center text-success">
            <h2 class="text-success">Дабро пожаловать в BigFamily</h2>
        </p>
    </div>
</div>

Views/User/MainPage.cshtml
@model Domain.Entities.User

@{
    ViewBag.Title = "MainPage";
    Layout = "~/Views/Shared/_Nav.cshtml";
}
<div class="col-md-3 col-lg-3 col-sm-3">
    <figure class="sign">
        <p>
            @if (Model.ImageData != null)
            {
                <img class="img-responsive" src="@Url.Action("GetImage", "User", new { Model.UserID})" />
            }
            else
            {
                <img class="img-responsive" src="~/Img/sampleuser@gmail.com.png" alt="Фото по умалчение" />
            }
        </p>
        <figcaption id="avatarName">@Model.Name  @Model.Surname</figcaption>
    </figure>

    <div class="menu">
        <div class="form-group">

           @*<a href="Photo/Albums?userId=@Model.UserID">photo</a>*@
         
            @*@Html.ActionLink("photo", "Albums", "Photo", new {userId=Model.UserID})*@
            @*<button class="btn btn-success btn-block" type="button"> Мои друзья </button>*@

            Меню:
            @Html.RouteLink("Просмореть фото", new
           {
               controller = "Photo",
               action = "Albums",
               userId = Model.UserID

           },
                    new { @class = "btn btn-success btn-block" })
            @Html.RouteLink("Добавить новое фото", new
           {
               controller = "Photo",
               action = "AddNewPhoto",
               userId = Model.UserID

           },
                    new { @class = "btn btn-success btn-block" })
            @Html.RouteLink("Выйти", new
           {
               controller = "User",
               action = "Login"

           },
                    new { @class = "btn btn-success btn-block" })

        </div>
    </div>
</div>  
<div class="col-md-9 col-lg-9 col-sm-9">
   @{Html.RenderAction("SliderOfPhoto", "Slider", new { userId = Model.UserID });}
</div>

Views/User/Registration.cshtml
@model WebUI.Models.RegistrationModel

@{
    ViewBag.Title = "Registration";
    Layout = "~/Views/Shared/_Nav.cshtml";
}

<center><h2>Регистрация</h2></center>
<div class="form-horizontal">
    @using (Html.BeginForm("Registration", "User",
    FormMethod.Post, new { enctype = "multipart/form-data" })) 
    {
         @Html.ValidationSummary()
          @Html.EditorFor(x => x.UserID, new { @class = "form-control" })
          <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
            <div class="col-sm-10">
                   @Html.TextBoxFor(x => x.Email, new {@class="form-control" })
            </div>
         </div>
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">Пароль</label>
            <div class="col-sm-10">
                   @Html.PasswordFor(x => x.Password, new {@class="form-control" })
            </div>
         </div>
         <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">Потвердмите пароль</label>
            <div class="col-sm-10">
                   @Html.PasswordFor(x=>x.ConfirmPassword, new {@class="form-control" })
            </div>
         </div>
         <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">Имя</label>
            <div class="col-sm-10">
                   @Html.TextBoxFor(x => x.Name, new {@class="form-control" })
            </div>
         </div>
         <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">Фамилия</label>
            <div class="col-sm-10">
                   @Html.TextBoxFor(x => x.Surname, new {@class="form-control" })
            </div>
         </div>
         <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">Номер телефона</label>
            <div class="col-sm-10">
                   @Html.TextBoxFor(x => x.NumberPhone, new { @class = "form-control" })
            </div>
         </div>
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">Дата рождения</label>
            <div class="col-sm-10">
                   @Html.EditorFor(x => x.Burthday, new { @class = "form-control" })
            </div>
         </div>
         <div class="form-group">
            <label  class="col-sm-2 control-label">Аватарка</label>
             <div class="col-sm-10">
                 <input type="file" name="Image" />
            </div>
         </div>
    <input type="submit" value="Save" />

    }
</div>