Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Abstract;
namespace WebUI.Controllers
{
    public class NavController : Controller
    {
        //
        // GET: /Nav/
        private IPhotoRepository repository;
        public NavController(IPhotoRepository repo)
        {
            repository = repo;
        }
        public PartialViewResult Menu(int userId, string album = null)
        {
            ViewBag.SelectedAlbum = album;
            IEnumerable<string> albums = repository.Photos
                .Where(x=>x.UserID==userId)
                .Select(x => x.Albom)
                .Distinct();
            ViewBag.UserId = userId;
            return PartialView(albums);
        }

    }
}

Controllers/PhotoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Entities;
using Domain.Abstract;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class PhotoController : Controller
    {
        private IPhotoRepository repository;
        public PhotoController(IPhotoRepository repo)
        {
            this.repository=repo;
        }
        //
        // GET: /Photo/

        public ViewResult Albums(int userId, string album)
        {
            

            PhotoModelView photosUser = new PhotoModelView
            {
                Photos = repository.Photos
                .Where(p => p.UserID == userId&&(album==null||p.Albom==album))
                .OrderBy(p => p.Name),
                CurrentAlbum=album

            };

            ViewBag.UserId = userId;
                   
             
            return View(photosUser);
        }
        
        public ViewResult AddNewPhoto(int userId)
        {
            return View("Edit",new Photo());
        }
        public ViewResult Edit(int photoId)
        {
            Photo photoForEdit = repository.Photos
                .FirstOrDefault(ph => ph.PhotoID == photoId);
            return View(photoForEdit);
        }
        [HttpPost]
        public ActionResult Edit(Photo photoUser, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    photoUser.ImageMimeType = image.ContentType;
                    photoUser.ImageData = new byte[image.ContentLength];
                    image.InputStream.Read(photoUser.ImageData, 0, image.ContentLength);
                }
                repository.SavePhoto(photoUser);
                return RedirectToAction("Albums", new { userId=photoUser.UserID });
            }
            else
            {
                return View(photoUser);
            }
        }
        public ActionResult Delete(int photoId)
        {
            Photo deletePhoto = repository.DeletePhoto(photoId);
            if(deletePhoto!=null)
            {
                TempData["messageForPhoto"] = string.Format("{0} была удалена", deletePhoto.Name);
            }
            return RedirectToAction("Albums", new { userId = deletePhoto.UserID });
        }
        public FileContentResult GetPhoto(int photoId)
        {
            Photo photo = repository.Photos.FirstOrDefault(ph => ph.PhotoID == photoId);
            if (photo!=null)
            {
                return File(photo.ImageData, photo.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
    }
}

Views/Photo/Albums.cshtml
@model WebUI.Models.PhotoModelView

@{

    ViewBag.Title = "Albums";
    Layout = "~/Views/Shared/_LayoutForPhoto.cshtml";
    
}




<div class="container">
   
    @{Html.RenderAction("Menu", "Nav", new { userId=ViewBag.UserId });}
    <div class="clearfix mosaicflow">
        @foreach (var ph in Model.Photos)
        {
            @*<div class="mosaicflow__item">
                <a class="fancyimage" rel="group" href="@Url.Action("GetPhoto", "Photo", new { ph.PhotoID})">
                    <img src="@Url.Action("GetPhoto", "Photo", new { ph.PhotoID})" />
                </a>
            </div>*@
            @*<div class="mosaicflow__item">
                    <a class="fancyimage" rel="group" href="~/Img/sampleuser@gmail.com.png">
                        <img src="~/Img/sampleuser@gmail.com.png" />
                    </a>
                </div>*@
            Html.RenderPartial("Shared/PhotoSummary", ph);

        }
        </div>
    </div>

Views/Photo/Edit.cshtml
@model Domain.Entities.Photo

@{
    ViewBag.Title = "Edit Photo";
    Layout = "~/Views/Shared/_Nav.cshtml";
    
}

<center><h2>Работа с фото</h2></center>
<div class="form-horizontal">
    @using (Html.BeginForm("Edit", "Photo",
    FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.ValidationSummary()
        @Html.EditorFor(x => x.PhotoID, new { @class = "form-control" })
        @Html.EditorFor(x => x.UserID, new { @class = "form-control" })
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">Название фото</label>
            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
            </div>
        </div>
               <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">Название альбома</label>
            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.Albom, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">Описание</label>
            <div class="col-sm-10">
                @Html.TextAreaFor(x => x.Description, new { @class = "form-control" })
                @Html.HiddenFor(x=>x.ImageMimeType)
                @Html.HiddenFor(x=>x.ImageData)
            </div>
        </div>
        if(Model.ImageData!=null)
        {
        @Html.Raw("<img width=\"150\" height=\"150\" class=\"img-responsive\" src=\"data:image/jpeg;base64,"
                                        + Convert.ToBase64String(Model.ImageData) + "\" />")
        }
      
            <div class="form-group">
            <label  class="col-sm-2 control-label">Фото</label>
             <div class="col-sm-10">
                 <input type="file" name="Image" />
            </div>
         </div>
        <input type="submit" value="Save" />

    }
</div>